#!/bin/bash


killall -9 gazebo & killall -9 gzserver & killall -9 gzclient
killall -9 rviz
kill $(pgrep bash)

gnome-terminal --title="gazeebo" -e "bash -c \"cd ~/my_ws ; source devel/setup.bash ; export TURTLEBOT3_MODEL=burger ; sed -e 's/\(<real_time_update_rate>\).*\(<\/real_time_update_rate>\)/<real_time_update_rate>1000000<\/real_time_update_rate>/g' src/MRS_236609/worlds/closed_room.world ;  roslaunch MRS_236609 multi_turtlebot3.launch ; $SHELL\""
# gnome-terminal --title="gazeebo" -e "bash -c \"cd ~/my_ws ; source devel/setup.bash ; export TURTLEBOT3_MODEL=burger ; sed -e 's/\(<real_time_update_rate>\).*\(<\/real_time_update_rate>\)/<real_time_update_rate>1000000<\/real_time_update_rate>/g' src/MRS_236609/worlds/closed_room.world ;  roslaunch turtlebot3_gazebo turtlebot3_stage_1.launch ; $SHELL\""
# gnome-terminal --title="Rviz" -e "bash -c \"cd ~/my_ws ; source devel/setup.bash ; export TURTLEBOT3_MODEL=burger ; sleep 10 ; roslaunch MRS_236609 multi_bringup.launch ; $SHELL\""
gnome-terminal --title="Python dirty" -e "bash -c \"cd ~/my_ws ; source devel/setup.bash ; export TURTLEBOT3_MODEL=burger ; sleep 5 ; rosrun MRS_236609 dirt_publisher_ex3.py ; $SHELL\""
# gnome-terminal --title="Python dummy agent" -e "bash -c \"cd ~/my_ws ; source devel/setup.bash ; export TURTLEBOT3_MODEL=burger ; sleep 5 ; rosrun MRS_236609 dummy_agent.py ; $SHELL\""