#!/bin/bash


killall -9 gazebo & killall -9 gzserver & killall -9 gzclient
killall -9 rviz
kill $(pgrep bash)

gnome-terminal --title="gazeebo" -e "bash -c \"cd ~/my_ws ; source devel/setup.bash ; export TURTLEBOT3_MODEL=waffle ; sed -e 's/\(<real_time_update_rate>\).*\(<\/real_time_update_rate>\)/<real_time_update_rate>1000000<\/real_time_update_rate>/g'  src/ros_submission/worlds/close_room_with_blue_red_balls.world ; roslaunch ros_submission multi_turtlebot3_red_blue.launch ; $SHELL\""
gnome-terminal --title="Rviz" -e "bash -c \"cd ~/my_ws ; source devel/setup.bash ; export TURTLEBOT3_MODEL=waffle ; sleep 10 ; roslaunch MRS_236609 multi_bringup.launch ; $SHELL\""
